<?php

require_once '/Users/sts-158imac/Sites/cloudfactory_php/lib/cloudFactory.php';

/**
* Test class for cloudFactory.
* Generated by PHPUnit on 2011-06-24 at 16:27:58.
*/
class cloudFactoryTest extends PHPUnit_Framework_TestCase
{
    /**
    * @var cloudFactory
    */
  protected $object;

  /**
  * Sets up the fixture, for example, opens a network connection.
  * This method is called before a test is executed.
  */
  protected function setUp()
  {
    $this->object  = new cloudFactory();
  }

  /**
  * Tears down the fixture, for example, closes a network connection.
  * This method is called after a test is executed.
  */
  protected function tearDown()
  {
  }

  /**
  * @test
  * @group line
  * @covers CloudFactory::createLine
  * createLine function should create a new Line Object and append the new line to cf object
  */
  public function createline(){
    $initial_count = count($this->object->getLines());
    $this->assertType('Line',$this->object->createLine("Transcription","Other","Transcribe My Podcast"));
    $this->assertGreaterThan($initial_count, count($this->object->getLines()));
  }
}
?>
