<?php

require_once '/Users/sts-158imac/Sites/cloudfactory_php/lib/Department.php';

/**
 * Test class for Department.
 * Generated by PHPUnit on 2011-06-24 at 16:28:49.
 */
class DepartmentTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Department
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Department;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
