<?php

require_once '/Users/sts-158imac/Sites/cloudfactory_php/lib/Output.php';

/**
 * Test class for Output.
 * Generated by PHPUnit on 2011-06-24 at 16:30:48.
 */
class OutputTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Output
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Output;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetUnitId().
     */
    public function testGetUnitId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetFinalOutputs().
     */
    public function testGetFinalOutputs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
