<?php

require_once '/Users/sts-158imac/Sites/cloudfactory_php/lib/Run.php';

/**
 * Test class for Run.
 * Generated by PHPUnit on 2011-06-24 at 16:31:14.
 */
class RunTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Run
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Run;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetOutput().
     */
    public function testGetOutput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
